/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SuppliesRouteImport } from './routes/supplies'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstructorsRouteImport } from './routes/instructors'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CampsRouteImport } from './routes/camps'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormsIndexRouteImport } from './routes/forms.index'
import { Route as FormSlugRouteImport } from './routes/form.$slug'
import { Route as FormsIdResponsesRouteImport } from './routes/forms.$id.responses'
import { Route as FormsIdEditRouteImport } from './routes/forms.$id.edit'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliesRoute = SuppliesRouteImport.update({
  id: '/supplies',
  path: '/supplies',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorsRoute = InstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CampsRoute = CampsRouteImport.update({
  id: '/camps',
  path: '/camps',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsIndexRoute = FormsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FormsRoute,
} as any)
const FormSlugRoute = FormSlugRouteImport.update({
  id: '/form/$slug',
  path: '/form/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsIdResponsesRoute = FormsIdResponsesRouteImport.update({
  id: '/$id/responses',
  path: '/$id/responses',
  getParentRoute: () => FormsRoute,
} as any)
const FormsIdEditRoute = FormsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => FormsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/audit-logs': typeof AuditLogsRoute
  '/camps': typeof CampsRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/forms': typeof FormsRouteWithChildren
  '/instructors': typeof InstructorsRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/supplies': typeof SuppliesRoute
  '/users': typeof UsersRoute
  '/form/$slug': typeof FormSlugRoute
  '/forms/': typeof FormsIndexRoute
  '/forms/$id/edit': typeof FormsIdEditRoute
  '/forms/$id/responses': typeof FormsIdResponsesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/audit-logs': typeof AuditLogsRoute
  '/camps': typeof CampsRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/instructors': typeof InstructorsRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/supplies': typeof SuppliesRoute
  '/users': typeof UsersRoute
  '/form/$slug': typeof FormSlugRoute
  '/forms': typeof FormsIndexRoute
  '/forms/$id/edit': typeof FormsIdEditRoute
  '/forms/$id/responses': typeof FormsIdResponsesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/audit-logs': typeof AuditLogsRoute
  '/camps': typeof CampsRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/forms': typeof FormsRouteWithChildren
  '/instructors': typeof InstructorsRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/supplies': typeof SuppliesRoute
  '/users': typeof UsersRoute
  '/form/$slug': typeof FormSlugRoute
  '/forms/': typeof FormsIndexRoute
  '/forms/$id/edit': typeof FormsIdEditRoute
  '/forms/$id/responses': typeof FormsIdResponsesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/audit-logs'
    | '/camps'
    | '/courses'
    | '/dashboard'
    | '/forms'
    | '/instructors'
    | '/login'
    | '/payments'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/students'
    | '/supplies'
    | '/users'
    | '/form/$slug'
    | '/forms/'
    | '/forms/$id/edit'
    | '/forms/$id/responses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/audit-logs'
    | '/camps'
    | '/courses'
    | '/dashboard'
    | '/instructors'
    | '/login'
    | '/payments'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/students'
    | '/supplies'
    | '/users'
    | '/form/$slug'
    | '/forms'
    | '/forms/$id/edit'
    | '/forms/$id/responses'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/audit-logs'
    | '/camps'
    | '/courses'
    | '/dashboard'
    | '/forms'
    | '/instructors'
    | '/login'
    | '/payments'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/students'
    | '/supplies'
    | '/users'
    | '/form/$slug'
    | '/forms/'
    | '/forms/$id/edit'
    | '/forms/$id/responses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  AuditLogsRoute: typeof AuditLogsRoute
  CampsRoute: typeof CampsRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  FormsRoute: typeof FormsRouteWithChildren
  InstructorsRoute: typeof InstructorsRoute
  LoginRoute: typeof LoginRoute
  PaymentsRoute: typeof PaymentsRoute
  ReportsRoute: typeof ReportsRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  StudentsRoute: typeof StudentsRoute
  SuppliesRoute: typeof SuppliesRoute
  UsersRoute: typeof UsersRoute
  FormSlugRoute: typeof FormSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplies': {
      id: '/supplies'
      path: '/supplies'
      fullPath: '/supplies'
      preLoaderRoute: typeof SuppliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructors': {
      id: '/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof InstructorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camps': {
      id: '/camps'
      path: '/camps'
      fullPath: '/camps'
      preLoaderRoute: typeof CampsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/': {
      id: '/forms/'
      path: '/'
      fullPath: '/forms/'
      preLoaderRoute: typeof FormsIndexRouteImport
      parentRoute: typeof FormsRoute
    }
    '/form/$slug': {
      id: '/form/$slug'
      path: '/form/$slug'
      fullPath: '/form/$slug'
      preLoaderRoute: typeof FormSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$id/responses': {
      id: '/forms/$id/responses'
      path: '/$id/responses'
      fullPath: '/forms/$id/responses'
      preLoaderRoute: typeof FormsIdResponsesRouteImport
      parentRoute: typeof FormsRoute
    }
    '/forms/$id/edit': {
      id: '/forms/$id/edit'
      path: '/$id/edit'
      fullPath: '/forms/$id/edit'
      preLoaderRoute: typeof FormsIdEditRouteImport
      parentRoute: typeof FormsRoute
    }
  }
}

interface FormsRouteChildren {
  FormsIndexRoute: typeof FormsIndexRoute
  FormsIdEditRoute: typeof FormsIdEditRoute
  FormsIdResponsesRoute: typeof FormsIdResponsesRoute
}

const FormsRouteChildren: FormsRouteChildren = {
  FormsIndexRoute: FormsIndexRoute,
  FormsIdEditRoute: FormsIdEditRoute,
  FormsIdResponsesRoute: FormsIdResponsesRoute,
}

const FormsRouteWithChildren = FormsRoute._addFileChildren(FormsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  AuditLogsRoute: AuditLogsRoute,
  CampsRoute: CampsRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  FormsRoute: FormsRouteWithChildren,
  InstructorsRoute: InstructorsRoute,
  LoginRoute: LoginRoute,
  PaymentsRoute: PaymentsRoute,
  ReportsRoute: ReportsRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  StudentsRoute: StudentsRoute,
  SuppliesRoute: SuppliesRoute,
  UsersRoute: UsersRoute,
  FormSlugRoute: FormSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
